export default [
  {
    adult: false,
    backdrop_path: '/wJzHFl5mq6JFbD6equTleJuzlnk.jpg',
    genre_ids: [16, 10765, 9648, 10759],
    id: 38464,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '青の祓魔師',
    overview:
      '故事以住在修道院中的少年「奥村燐」作為主角。繼承了青焰魔之血的他，他的資優生雙胞胎弟弟「雪男」以 13 歲的最年少記錄就獲得了驅魔師稱號，然而燐卻完全不知道自己未來想要做什麼…。就在某日，燐的面前出現了一位自稱為其父親的魔神(青焰魔)，並計畫將他帶到惡魔居住的虛無界。而修道院的神父、同時也是燐的養父「藤本」為了保護燐而喪命，燐因此決意成為最強驅魔師並為養父報仇，打倒魔神。',
    popularity: 249.658,
    poster_path:
      'https://image.tmdb.org/t/p/w500/aUWyfqepOswBPwjSC5ccPPeZxyK.jpg',
    first_air_date: '2011-04-17',
    name: '青之驅魔師',
    vote_average: 7.9,
    vote_count: 433,
  },
  {
    adult: false,
    backdrop_path: '/z0YhJvomqedHF85bplUJEotkN5l.jpg',
    genre_ids: [16, 10759, 10765],
    id: 31910,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ナルト 疾風伝',
    overview:
      '在終結山谷的激戰過了二年半之後，鳴人結束與自來也的修行之旅回到了木葉忍者村，與成為醫療忍者的小櫻以及感覺和以前一樣的卡卡西組成小隊，並再次接受搶奪鈴鐺的生存演習，已經成長的鳴人與小櫻成功通過演習。而就在鳴人與夥伴們重逢之時，「曉」的魔掌開始伸向已經成為風影的我愛羅。',
    popularity: 257.749,
    poster_path:
      'https://image.tmdb.org/t/p/w500/cR0nwH0QP4OKFIQNeF2OAPv3xfy.jpg',
    first_air_date: '2007-02-15',
    name: '火影忍者疾風傳',
    vote_average: 8.5,
    vote_count: 8107,
  },
  {
    adult: false,
    backdrop_path: '/lTGTQ02Bci6SIncqE1aljuy3NK7.jpg',
    genre_ids: [16, 35],
    id: 99466,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ヤリチン☆ビッチ部',
    overview: '',
    popularity: 297.099,
    poster_path:
      'https://image.tmdb.org/t/p/w500/5bAcvgpy0yGUXkQJV2RE52dIvUk.jpg',
    first_air_date: '2018-09-21',
    name: 'ヤリチン☆ビッチ部',
    vote_average: 7.3,
    vote_count: 37,
  },
  {
    adult: false,
    backdrop_path: '/yErVUZkLVak2ICxFC7mMfl3vcNP.jpg',
    genre_ids: [16, 10759, 35, 10765],
    id: 205050,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'シャングリラ・フロンティア',
    overview:
      '如果世界上的遊戲有100款神作，那麼也就有存在著1000款糞作。這是深愛糞作也為糞作所鍾愛的男人「陽務樂郎」，挑戰與糞作完全極端的神作「香格里拉·開拓異境」的故事。 原著網路小說累計超過5億點閱，未出小說單行本便直接在「週刊少年Magazine」進行漫畫連載，並在這擁有60年以上歷史的漫畫雜誌達成史上首次的讀者問卷四連冠！ 以每個人都有過的遊戲體驗描寫全新感覺的奇幻故事，讓沉浸在過去回憶的大人們&活在先進科技中的年輕人一同體驗踏上新冒險的興奮心情。 一位糞作獵手挑戰神作，最棒的「遊戲×奇幻」冒險譚，開幕！',
    popularity: 334.37,
    poster_path:
      'https://image.tmdb.org/t/p/w500/6YciPUr0pnC2ofksdF9JPID69k4.jpg',
    first_air_date: '2023-10-01',
    name: '香格里拉・開拓異境~糞作獵手挑戰神作~',
    vote_average: 7.9,
    vote_count: 99,
  },
  {
    adult: false,
    backdrop_path: '/ubggJhb6QysnXVercF4ij9RLJJu.jpg',
    genre_ids: [16, 10759, 10765],
    id: 31572,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ルパン三世',
    overview:
      '故事敘述怪盜紳士魯邦一族的第三代繼承人「魯邦三世」，擁有智商300的天才頭腦，是個逍遙且極具正義感的小偷，精通藝術性的盜竊技巧。他與嗜好煙酒的槍手「次元大介」、為之鍾情的神秘女盜「峰不二子」、精通居合斬的第十三代「石川五衛門」以及常因為眨眼工夫就被魯邦逃脫而苦惱的「錢形警部」，共同上演了一部怪盜喜劇。',
    popularity: 178.741,
    poster_path:
      'https://image.tmdb.org/t/p/w500/l8Vq3rUG3xYwySPVUx5dkjSaesi.jpg',
    first_air_date: '1971-10-24',
    name: '魯邦三世',
    vote_average: 8,
    vote_count: 106,
  },
  {
    adult: false,
    backdrop_path: '/lysUnU6V0VfcthDbviuVlIqgHOR.jpg',
    genre_ids: [16, 35, 10759],
    id: 120089,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'SPY×FAMILY',
    overview:
      '每一個人，都有不能展現給任何人看的一面 ──\n\n這是個世界各國都在檯面下進行激烈情報戰的時代。東國與西國，兩國之間已持續冷戰了十多年。隸屬於西國情報局對東課「WISE」的幹練間諜〈黃昏〉，被指派一項極機密任務，奉命接近威脅東西和平的危險人物，要刺探出東國國家統一黨黨魁 ─ 唐納文．戴斯蒙德的戰爭計畫。其任務名為 ─ 行動代號〈梟〉。任務內容是：「在一週內組好家庭，並潛入戴斯蒙德兒子所就讀的名校。」於是〈黃昏〉扮起精神科醫生 ─ 洛伊德．佛傑，開始組織家庭。然而，他找到的女兒 ─ 安妮亞是會讀心的超能力者，妻子 ── 約兒則是位暗殺者！\n\n由於利害一致，三人便互相隱瞞真實身分，並展開共同生活。世界的和平，就這樣被託付給狀況百出的臨時家庭 ──',
    popularity: 242.731,
    poster_path:
      'https://image.tmdb.org/t/p/w500/iWz0DzeJZpXpGCzvLTj6gkWjnCR.jpg',
    first_air_date: '2022-04-09',
    name: 'SPY×FAMILY 間諜家家酒',
    vote_average: 8.6,
    vote_count: 1882,
  },
  {
    adult: false,
    backdrop_path: '/bFKKyCI89Xq98Gul8cGox8K3sZa.jpg',
    genre_ids: [16, 10759, 10765],
    id: 46298,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'HUNTER×HUNTER',
    overview:
      '這位小男孩為了達成夢想，跟父親一樣成為傳奇獵人，必須通過一項艱難的試驗，並找到失蹤的爸爸。',
    popularity: 246.85,
    poster_path:
      'https://image.tmdb.org/t/p/w500/9WxfAQquTun9ATkV6iAeFHMkqxv.jpg',
    first_air_date: '2011-10-02',
    name: '全職獵人',
    vote_average: 8.6,
    vote_count: 1750,
  },
  {
    adult: false,
    backdrop_path: '/2WBO3C7CjsOTT5wgi9Inn5iQhVv.jpg',
    genre_ids: [16, 35, 18, 9648],
    id: 46195,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '化物語',
    overview:
      '故事講述高中生阿良良木曆在機緣巧合之下，無意間發現2年中從未交流過的同班同學——戰場原黑儀的秘密。為了不讓自己的秘密暴露，戰場原不斷威脅阿良良木。但實際上，阿良良木本身與戰場原一樣，隱藏著不為人知的詭異秘密。而在這個城市內，尚有更多怪物出沒……',
    popularity: 194.419,
    poster_path:
      'https://image.tmdb.org/t/p/w500/rHqf9HldXt2wbHR3LrUMNuMC343.jpg',
    first_air_date: '2009-07-03',
    name: '化物語',
    vote_average: 8.1,
    vote_count: 458,
  },
  {
    adult: false,
    backdrop_path: '/xMgzRUA1RjxLQn05oJ8IFbf06AO.jpg',
    genre_ids: [16, 10759, 35, 10765],
    id: 259140,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'らんま1/2',
    overview:
      '天道茜遇見新未婚夫早乙女亂馬，他雖是練武奇才，卻有一點和別人不一樣：一碰到冷水就會離奇變成女生。',
    popularity: 223.394,
    poster_path:
      'https://image.tmdb.org/t/p/w500/gXpQ4FE3b4TlOf2rOk6P8P3Pc8x.jpg',
    first_air_date: '2024-10-06',
    name: '亂馬 1/2',
    vote_average: 8.3,
    vote_count: 38,
  },
  {
    adult: false,
    backdrop_path: '/nDDZ9yQoQpC9i3Q9W9EC7QdcPsX.jpg',
    genre_ids: [10759, 16, 35, 10765, 10762],
    id: 3570,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '美少女戦士セーラームーン',
    overview:
      '美麗可愛的月野兔是一名正就讀初中的女孩，她學業平平，任性嬌弱，儼然是生活在大都會普普通通的女孩子們中的平凡一員。可是，在遇到了那隻會說話的小貓露娜之後，月野的人生髮生天翻地覆的變化。她不僅可以變身成為擁有神奇能力的水手月亮，還漸漸知曉了自己前世今生的秘密。為了保衛地球，挫敗黑暗帝國的野心，月野和水野亞美、火野麗、木野真琴、愛野美奈子等人結成美少女戰士，與罪惡展開了連番激戰，在此過程中，她與命中註定的愛人地場衛的浪漫戀情也悄然上演……本片根據漫畫家武內直子的經典同名原著改編。',
    popularity: 189.887,
    poster_path:
      'https://image.tmdb.org/t/p/w500/9Uz8Me0l0hNtMOlrdpH64wrYFa8.jpg',
    first_air_date: '1992-03-07',
    name: '美少女戰士',
    vote_average: 8.4,
    vote_count: 944,
  },
  {
    adult: false,
    backdrop_path: '/2w8FaLwwJTWr6ExUMeVgT2Th5YT.jpg',
    genre_ids: [16, 35, 18, 10759],
    id: 42705,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'はじめの一歩',
    overview:
      '家中經營釣魚船、總是被欺負的少年幕之內一步，和後來成為世界冠軍的鷹村守相遇，開啟了拳擊的人生。以描寫進入鴨川會館，努力成為偉大拳手的故事。特色是仔細地描寫了同伴與對手間的戰鬥，成為長期連載作品，是平成時代代表『週刊少年Magazine』的看板漫畫之一。各話以「Round.○○」的連續數字作區隔，在Fan Book也以「R109」之類的方式記載。\n\n在許多登場人物上投射了輝煌拳擊歷史的人物形象，在虛構作品中成功地重現了「即使得到一瞬間的光輝，在世界上仍然是無名小卒」的表象。森川本身也常接觸拳擊世界，在雜誌上刊載了為年輕選手加油的話語等。',
    popularity: 203.523,
    poster_path:
      'https://image.tmdb.org/t/p/w500/umMYjHm7FjsyllUnC8lWDy9rrZQ.jpg',
    first_air_date: '2000-10-03',
    name: '第一神拳',
    vote_average: 8.653,
    vote_count: 1059,
  },
  {
    adult: false,
    backdrop_path: '/j0meXFRhxwk13yUaLBSUtqOwx7I.jpg',
    genre_ids: [10759, 16, 35, 10762, 10765, 10751],
    id: 67667,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ベイブレードバースト',
    overview: '',
    popularity: 165.778,
    poster_path:
      'https://image.tmdb.org/t/p/w500/7gNPKHaW3VB2UlDVxpfcTQBPk9N.jpg',
    first_air_date: '2016-04-04',
    name: 'ベイブレードバースト',
    vote_average: 8.3,
    vote_count: 312,
  },
  {
    adult: false,
    backdrop_path: '/7apk7MDXON2zZ2ntXgaIusHrUNa.jpg',
    genre_ids: [16, 35],
    id: 27845,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'テニスの王子様',
    overview:
      '新學期開始，青春學園實力強勁的網球社來了一個國一新生 - 越前龍馬，在美國青少年網球大賽上連續四次獲勝，被譽為網球天才少年。越前龍馬在青春學園網球社遇到了實力強勁的學長們，但他以驚人的實力，最終贏得了學長們的認可正式加入了校隊，開始了通往全國大賽的奮鬥之路。',
    popularity: 152.112,
    poster_path:
      'https://image.tmdb.org/t/p/w500/kBs31CCVdXBh2XcKQH6SzSsZk8p.jpg',
    first_air_date: '2001-10-10',
    name: '網球王子',
    vote_average: 8.3,
    vote_count: 128,
  },
  {
    adult: false,
    backdrop_path: '/hiYSi32T8y67KicU6JpMAx4IHu9.jpg',
    genre_ids: [16, 35, 10765],
    id: 63164,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ケロロ軍曹',
    overview:
      '199X世界普遍流行世紀末預言的時代，在日向家突然降臨了來自外星球卻酷似青蛙的外星人─KERORO軍曹。身負侵略地球使命的KERORO軍曹降臨地球後，卻輕易被夏美和冬樹抓住，在冬樹溫情及強烈的好奇心之下，他開始住在日向家中成為他們的食客，一心想佔領地球的軍曹，不但無法達成任務，還陰錯陽差反而在地球上過著愉快的佣人般的生活。',
    popularity: 159.885,
    poster_path:
      'https://image.tmdb.org/t/p/w500/7OfSkenYWY1t6IxeRX4loIhIpoV.jpg',
    first_air_date: '2004-04-03',
    name: 'Keroro 軍曹',
    vote_average: 7.3,
    vote_count: 23,
  },
  {
    adult: false,
    backdrop_path: '/mLKN1dsimKPiXCZ48KED0X8a02t.jpg',
    genre_ids: [16, 10759, 10765],
    id: 45790,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ジョジョの奇妙な冒険',
    overview:
      '在一次意外中，喬納森（興津和幸配音）的父親喬斯達爵士（菅原正志配音）被陌生少年迪奧布蘭度（子安武人配音）所救，善良的爵士收留了自稱無依無靠的迪奧，後者則以養子的身份正式進入了喬斯達家族的大門。在他人的眼中，迪奧是一個優秀正直的少年，可是，只有經歷過迪奧殘酷欺辱的喬納森才知道，在迪奧光鮮的面具後面，隱藏著一顆邪惡的心。果不其然，隨著年齡的增長，迪奧開始覬覦起了喬斯達家族的龐大家產。無意間，迪奧發現了能夠使人變得強大的石鬼面具，為了獲得更多的財富和權力，迪奧毫不猶豫的帶上了面具。在成為了恐怖的吸血鬼后，迪奧開始了對喬斯達家族的瘋狂報復。為了替父親和整個家族報仇，喬納森開始修煉唯一能夠打敗吸血鬼的波紋氣功，面對著強大的敵人極其黨羽，喬納森能夠獲得最終的勝利嗎？',
    popularity: 158.942,
    poster_path:
      'https://image.tmdb.org/t/p/w500/v3tg5I7DkyXjSVgV0MINbNaeR12.jpg',
    first_air_date: '2012-10-06',
    name: 'JOJO的奇妙冒險',
    vote_average: 8.577,
    vote_count: 1381,
  },
  {
    adult: false,
    backdrop_path: '/qZXhYuCZR6lkspbu400oWwh6uCs.jpg',
    genre_ids: [16, 35, 10751, 10762, 10765],
    id: 194916,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ちいかわ',
    overview: '',
    popularity: 195.66,
    poster_path:
      'https://image.tmdb.org/t/p/w500/knJg7Uyhg66GPHfGRwadD2r2uew.jpg',
    first_air_date: '2022-04-04',
    name: '吉伊卡哇',
    vote_average: 8.3,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: '/j9fRIimor0AMFJR9kjZubXcABzZ.jpg',
    genre_ids: [16, 10759, 10765],
    id: 94664,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '無職転生 ～異世界行ったら本気だす～',
    overview:
      '「我要在這個異世界拿出真本事！」34歲、處男、無職的家裡蹲尼特男。他在雙親葬禮當天被趕出家門的瞬間，就因為遭卡車碾過而喪命。等他重新醒來，發現自己在劍與魔法的異世界轉生成了小嬰兒！曾活得跟垃圾一樣的男人，發誓要做為少年魯迪烏斯在異世界認真過活！等待著魯迪烏斯的，是與蘿莉魔術師、有著妖精耳朵卻使用男性化自稱的美少女、兇暴傲嬌大小姐，以及其他各式各樣人物的相遇，以及殘酷的冒險與戰鬥。全新的人生就此展開！「人生重來」奇幻故事，現在開幕！',
    popularity: 192.961,
    poster_path:
      'https://image.tmdb.org/t/p/w500/aWUXopLwAypXTsHO8HYmsMazpVI.jpg',
    first_air_date: '2021-01-11',
    name: '無職轉生～到了異世界就拿出真本事～',
    vote_average: 8.536,
    vote_count: 1128,
  },
  {
    adult: false,
    backdrop_path: '/lE501tGuJt5rgPsbdYxmbh3vGWx.jpg',
    genre_ids: [16, 10759, 10762],
    id: 91426,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'ジュエルペット',
    overview: '',
    popularity: 149.282,
    poster_path:
      'https://image.tmdb.org/t/p/w500/750II7VWRTSedLfpv7n6L1iVNLC.jpg',
    first_air_date: '2009-04-05',
    name: 'ジュエルペット',
    vote_average: 8.8,
    vote_count: 5,
  },
  {
    adult: false,
    backdrop_path: '/htD5SJpPOvkmAowU80KrWnN59WO.jpg',
    genre_ids: [16, 35, 10765, 10759],
    id: 119495,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: '陰の実力者になりたくて！',
    overview:
      '「吾名闇影。乃潛伏於闇影之中，狩獵闇影之人……」\n\n少年席德憧憬著以路人身分隱藏自身力量，不為人知地介入故事，展現實力的「影之強者」──轉生到異世界後，企圖充分享受這種設定的席德，為了擊潰妄想中的敵人「黑暗教團」而暗中大顯身手。\n\n然而，這個教團似乎真的存在……？\n\n同時，因為他順勢收為部下的少女們「會錯意」，席德在一無所知的狀態下成了真正的「影之強者」，一行人建立起來的「闇影庭園」，將殲滅這世上的黑暗──!!',
    popularity: 179.464,
    poster_path:
      'https://image.tmdb.org/t/p/w500/3C44kJOcKSGMAl8wvUXDuHUsSm3.jpg',
    first_air_date: '2022-10-05',
    name: '我想成為影之強者！',
    vote_average: 8.03,
    vote_count: 117,
  },
  {
    adult: false,
    backdrop_path: '/saZTZ8t7rgC5OysidZoUCqMVS4o.jpg',
    genre_ids: [10759, 16, 35],
    id: 36046,
    origin_country: ['JP'],
    original_language: 'ja',
    original_name: 'シティーハンター',
    overview:
      '該作品以生動幽默的風格塑造了一位身懷絕技而又好色、可愛又可恨的私人偵探「冴羽獠」，他與個性開朗的女孩「槇村香」共同從事著以「城市獵人」為名的私人偵探事務。委託者只要在新宿車站的留言板上寫下「XYZ」字樣，他們就會接受委託。通常情況下，委託者必須是年輕貌美的女性。在一次次艱險的委託任務中，城市獵人以其獨有的方式鏟除著城市中的罪惡。',
    popularity: 132.221,
    poster_path:
      'https://image.tmdb.org/t/p/w500/9zOHCNEeisH472vp8Y9eVI7WmVK.jpg',
    first_air_date: '1987-04-06',
    name: '城市獵人',
    vote_average: 7.9,
    vote_count: 47,
  },
];
