export default [
  {
    adult: false,
    backdrop_path: '/8BSxCJhKfsPPWgxRFFB46ysnEgB.jpg',
    genre_ids: [16, 14, 18],
    id: 507411,
    original_language: 'ja',
    original_title: '劇場版 夏目友人帳 ～うつせみに結ぶ～',
    overview:
      '高中生夏目貴志有靈異體質，能看見別人所看不到的。當他得到祖母玲子的遺物「友人帳」之後，不論白天或晚上，開始有各式各樣的妖怪紛紛找上門！  原來玲子也和貴志一樣有靈異體質，大家都對她敬而遠之。玲子因為十分寂寞，便到處向妖怪下戰書，並要戰敗的妖怪交出名字，訂立服從的契約。而貴志拿到的，正是這本寫有眾多妖怪名字，能夠號令百妖，力量引人覬覦的「友人帳」！  貴志在得知事情原委之後，決心要將「友人帳」上的名字一一還給被玲子擊敗的妖怪。而想要不費吹灰之力拿到友人帳的妖怪「貓咪老師」，則自願當保鑣，保護貴志和「友人帳」，共同踏上妖怪之旅！',
    popularity: 57.097,
    poster_path:
      'https://image.tmdb.org/t/p/w500/4zfdUR2hXK35F2ZnXcVGo5vRjD7.jpg',
    release_date: '2018-09-29',
    title: '劇場版 夏目友人帳 ～緣結空蟬～',
    video: false,
    vote_average: 7.4,
    vote_count: 23,
  },
  {
    adult: false,
    backdrop_path: '/uj2duAkn6zUmRSbjyEr7XUeIWsJ.jpg',
    genre_ids: [16, 28, 27],
    id: 1083862,
    original_language: 'ja',
    original_title: 'バイオハザード：デスアイランド',
    overview:
      'D.S.O. 探員里昂接獲任務前往惡魔島聯邦監獄「阿爾卡特拉斯島」，從綁架者手中解救掌握某機密情報的安東尼奧·泰勒博士，但一名神祕女子出現並阻止了他。同一時間，反生物恐怖組織「BSAA」探員 克里斯、克蕾兒兄妹檔、吉兒與蕾貝卡正調查舊金山最新爆發的殭屍感染疫情，一行人從被沖上海灘的虎鯨屍體上的咬痕中檢測出T病毒，而一切源頭指向惡魔島。 主角們一同前往惡魔島調查真相，殊不知這一切皆是有人暗中安排的陰謀，五人齊聚面對迎面而來的種種危機。',
    popularity: 76.344,
    poster_path:
      'https://image.tmdb.org/t/p/w500/ovwtJawAgD3aXFDKDfsjmRCgZ8x.jpg',
    release_date: '2023-06-22',
    title: '惡靈古堡：死亡島',
    video: false,
    vote_average: 7.4,
    vote_count: 974,
  },
  {
    adult: false,
    backdrop_path: '/s974GBBFZ1I4SlZHFu2XIffk1dv.jpg',
    genre_ids: [16, 12, 28, 14, 10402],
    id: 900667,
    original_language: 'ja',
    original_title: 'ONE PIECE FILM RED',
    overview:
      '美音是世界上最受人喜愛的歌手。聲音在隱藏其特徵的同時發出，被形容為「另一個維度」。她第一次出現在公眾面前的現場表演將舉行。五顏六色的海賊注視著海軍，以及草帽一伙所有人都期待著她的聲音，而全世界期待已久的歌聲即將在大廳里迴蕩。這個故事源於美音是「紅髮傑克的女兒」的震驚事實。嚟自四方八面的人馬為爭奪美音而爆發出一場激烈的爭奪戰。',
    popularity: 81.908,
    poster_path:
      'https://image.tmdb.org/t/p/w500/7BwSqu2nRRwHmMXhr72phz3Tv6w.jpg',
    release_date: '2022-08-06',
    title: '航海王：紅髮歌姬',
    video: false,
    vote_average: 7.2,
    vote_count: 997,
  },
  {
    adult: false,
    backdrop_path: '/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg',
    genre_ids: [12, 14, 16],
    id: 128,
    original_language: 'ja',
    original_title: 'もののけ姫',
    overview:
      '在古老的年代裡，所有的森林均由守護神守護著，其中一支隱匿在山裡的族群，已享受數百年的太平盛世，不料，一隻受邪魔詛咒的山豬竟對該族攻擊。混亂中，英勇的族人阿席達卡殺了山豬，卻因此受傷，並中了邪魔的詛咒，生命危在旦夕。為破解咒語，阿席達卡遠赴他鄉，希望為自己和族人找出一條生路。在這趟旅程中，他意外結識了從小由山犬撫養長大的魔法公主。而為了守護森林，魔法公主不惜與敵人展開一場你死我活的戰役。在這場大自然與人類的對決中，阿席達卡能夠阻止大殺戮的發生，順利解除身上的詛咒嗎？',
    popularity: 56.838,
    poster_path:
      'https://image.tmdb.org/t/p/w500/nBBnjdKb2QEB1A1HKz56rvCudQc.jpg',
    release_date: '1997-07-12',
    title: '魔法公主',
    video: false,
    vote_average: 8.336,
    vote_count: 7969,
  },
  {
    adult: false,
    backdrop_path: '/vW7lwVHkRePHzayZfoKOyYBeZqO.jpg',
    genre_ids: [16, 12, 35, 10751],
    id: 1221404,
    original_language: 'ja',
    original_title: '映画クレヨンしんちゃん オラたちの恐竜日記',
    overview:
      '這個暑假，主打近距離觀察復活的恐龍的主題樂園「恐龍島」在東京開幕了。小新與春日部防衛隊，受邀至這座備受矚目的樂園參觀。與此同時，野原家的愛犬小白，在春日部河畔遇見了小恐龍那那。那那很快地與他們成為好友，共度這個充滿回憶的暑假。然而，那那其實有一個驚人的祕密。就在此時，「恐龍島」上發生了恐龍逃脫事件……。',
    popularity: 82.425,
    poster_path:
      'https://image.tmdb.org/t/p/w500/dTBhi2Y674JHaAktl550vpmxjF5.jpg',
    release_date: '2024-08-09',
    title: '電影蠟筆小新：我們的恐龍日記',
    video: false,
    vote_average: 8.7,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: '/qS2aqswgzYeSyzJd10L3LjrQOSk.jpg',
    genre_ids: [16, 18, 14],
    id: 773621,
    original_language: 'ja',
    original_title: '夏目友人帳 石起こしと怪しき来訪者',
    overview:
      '《喚石》篇  夏目在森林中遇見小妖怪－「三美」，據它說，它身負著名為「喚石」的職責，負責將具備神格名叫「岩鐵」的妖怪從沉睡中喚醒。不過貓咪老師和妖怪們垂涎任務完成後能得到的美酒獎賞，計畫要奪取喚石一職。夏目擔心三美，決心出手相助......。  《可疑的訪客》篇  田沼身邊出現一位不可思議的客人。每天都會出現在他身邊，只跟他說了一些話便離去。  夏目得知該位客人的真實身分是妖怪後雖然很擔心田沼，但田沼本人卻對跟妖怪的交流樂在其中。雖然這妖怪似乎無意作惡，但田沼的身體卻日漸虛弱......。',
    popularity: 67.953,
    poster_path:
      'https://image.tmdb.org/t/p/w500/aoR9qpLtjdfgCQyeMBwcaQRSVhh.jpg',
    release_date: '2021-01-16',
    title: '夏目友人帳 特別上映版：喚石與可疑訪客',
    video: false,
    vote_average: 7.3,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: '/7lLtUDuBqkL3VqPOOlJuVUNPL0d.jpg',
    genre_ids: [16, 878, 28],
    id: 34433,
    original_language: 'ja',
    original_title: 'ドラゴンボールＺ 燃え尽きろ!!熱戦・烈戦・超激戦',
    overview:
      '劇場版第11作，正序第8作。  賽亞人餘黨帕拉格斯帶著他的兒子佈羅利大肆破壞南銀河，最終父子二人降臨地球，請求貝吉塔登基成為新貝吉塔行星的國王。利令智昏的貝吉塔相信了他的請求，為了建立宇宙最強大的帝國，他隨帕拉格斯父子前往新貝吉塔行星。  對此疑竇叢生的特蘭克斯、悟飯等人為探明真相，隨之前往，最終發現帕拉格斯欲借貝吉塔的力量統治宇宙的野心。一場大戰在所難免。然而令龍珠戰士始料未及的是，外表瘦小軟弱的布羅利體內竟隱藏著極為強大的力量。他所變身的超級賽亞人成為了每一個龍珠戰士的噩夢。銀河系危在旦夕……',
    popularity: 82.401,
    poster_path:
      'https://image.tmdb.org/t/p/w500/vbb9INpvNJtOx2mHWRrAYs0RIFN.jpg',
    release_date: '1993-03-06',
    title: '七龍珠Z：燃燒!熱戰・烈戰・超激戰',
    video: false,
    vote_average: 7.2,
    vote_count: 903,
  },
  {
    adult: false,
    backdrop_path: '/xfZ2u86Tui0aTKcPYcKGStzxWZv.jpg',
    genre_ids: [28, 16, 18, 14, 10749],
    id: 283984,
    original_language: 'ja',
    original_title: '劇場版「Fate/stay night [Heaven’s Feel]」Ⅰ.presage flower',
    overview:
      '「假如我變成壞人的話，學長就不會原諒我了吧？」少年想要守護少女，僅此而已的故事。  魔術師〈MASTER〉和英靈〈SERVANT〉，圍繞著能夠實現所有願望的許願機「聖杯」而戰鬥——在「聖杯戰爭」發生的10年後，冬木市又一次掀起了戰爭。  前代「聖杯戰爭」的參加者衛宮切嗣的養子・衛宮士郎繼承了遺志，終於下定決心參戰。  士郎的身邊，陪伴著仰慕他的少女——間桐櫻。她每天早晨晚上都來到衛宮家，為他打掃房間和製作料理，孑然一身的她和士郎度過了平穩而又溫情的日常。  但是隨著戰爭的開始，冬木市街道上到處發生著殺人事件，險惡的空氣開始流動。所以士郎決定讓櫻留宿在自己家裡。  士郎召喚出從者・Saber的同時，和身為正統魔術師的遠阪凜結盟面對「聖杯戰爭」。但是，這場戰爭由於某些人的暗中策劃而發出不和諧音，開始變得扭曲了。',
    popularity: 56.877,
    poster_path:
      'https://image.tmdb.org/t/p/w500/5paSJPgjceP4F19r4H5T41Rpz7R.jpg',
    release_date: '2017-10-14',
    title: "Fate/stay night [Heaven's Feel]  I.預示之花",
    video: false,
    vote_average: 7.5,
    vote_count: 234,
  },
  {
    adult: false,
    backdrop_path: '/rQNmrceWbPYV9JDYknlOYRjcezI.jpg',
    genre_ids: [16, 28, 878],
    id: 39108,
    original_language: 'ja',
    original_title: 'ドラゴンボールZ 龍拳爆発!!悟空がやらねば誰がやる',
    overview:
      '晴朗的一天，悟飯和比迪麗正在教室上課，這是接到一條求助信息。原來有個老頭準備跳樓自殺，他們連忙化身賽亞超人前去營救。從這個奇怪的老頭口中，他們得知距今一千五百年前，南銀河科納茲星球曾有一名超級英雄塔皮歐，後來不知何種原因被困在音樂盒中。為防止即將到來的大災難，孫悟空父子在老頭的請求下召喚了神龍，終於救出塔皮歐，卻發現塔皮歐並不領情，而老頭似乎又隱藏著某種陰謀。此後不久，一個邪惡的怪物出現在都市之中，它只有下半截身體，上半截則被封印在塔皮歐的體內。一切昭然若顯，龍珠戰士則面臨巨大的危機……',
    popularity: 64.733,
    poster_path:
      'https://image.tmdb.org/t/p/w500/ptPTWOxojBJtAGyH1dhtDpcudvF.jpg',
    release_date: '1995-07-15',
    title: '七龍珠Z：龍拳爆發!!悟空捨我其誰',
    video: false,
    vote_average: 7.3,
    vote_count: 709,
  },
  {
    adult: false,
    backdrop_path: '/sZIJkZPKySo398Me4HLeUM7eCy0.jpg',
    genre_ids: [16, 28, 14],
    id: 20982,
    original_language: 'ja',
    original_title: '劇場版 NARUTO -ナルト- 疾風伝',
    overview:
      '紫苑─鬼之國巫女使用自己的特殊能力，預言鳴人即將死亡。她擁有兩種能力，封印魔物的能力和預言他人死亡的能力。由於被「鬼」追殺，所以接受木葉忍者的保護。  這 次故事的舞臺是「鬼之國」，據知當地有「惡鬼」這種只存在傳說中的怪物出現。因為紫苑的能力，所以那些魔物追殺紫苑，而鳴人等人就負責保護紫苑，被紫苑預 言即將死亡的鳴人如果不離開紫苑，就會步入死亡，但失去鳴人保護的紫苑定會被魔物所殺。世上只有紫苑一人會封印魔物，如果紫苑死了，那世界定會踏上滅亡之 路，所以鳴人決定留下保護紫苑，挑戰那不會失效的「死之預言」。',
    popularity: 60.883,
    poster_path:
      'https://image.tmdb.org/t/p/w500/42wTMmhYstM01tlaXWWfKn0RqPr.jpg',
    release_date: '2007-08-04',
    title: '火影忍者疾風傳劇場版：鳴人將死',
    video: false,
    vote_average: 7.392,
    vote_count: 975,
  },
  {
    adult: false,
    backdrop_path: '/921vUyXdfIYpaXqu5Lnf3nVb4IJ.jpg',
    genre_ids: [16, 28, 14],
    id: 810693,
    original_language: 'ja',
    original_title: '劇場版 呪術廻戦 0',
    overview:
      '自幼感情極好的乙骨憂太與祈本里香約好長大後要結婚，卻不料里香因死亡車禍化為強大怨靈依附在憂太身邊，為此所苦的憂太一心求死，之後在五條悟的帶領下進入咒術高專結識了新同學：禪院真希、狗卷棘與熊貓，他決定在這裡找到活下去的自信並解除里香的詛咒。意欲奪取里香強大怨靈力量的夏油傑宣布在12月24日舉行「百鬼夜行」，在新宿與京都釋出上千個詛咒。面臨如此重大浩劫，憂太能否阻止夏油的野心並解開里香的詛咒？',
    popularity: 60.598,
    poster_path:
      'https://image.tmdb.org/t/p/w500/qiodOI39faRytzKvmq1C8IUjxaX.jpg',
    release_date: '2021-12-24',
    title: '劇場版 咒術迴戰 0',
    video: false,
    vote_average: 8.171,
    vote_count: 1390,
  },
  {
    adult: false,
    backdrop_path: '/uicia399gyMGE1smatJ41M0CtFx.jpg',
    genre_ids: [16, 28, 12, 14],
    id: 505262,
    original_language: 'ja',
    original_title: '僕のヒーローアカデミア THE MOVIE ～2人の英雄～',
    overview:
      '本作電影時間線在動畫第二季和第三季之間「空白的夏天」，故事舞台為是一座以巨大人口移動都市「I·ISLAND」。出久等人造訪I·ISLAND，並且與無個性的少女梅麗莎相遇，而年輕時的歐爾麥特也在本作電影中登場。',
    popularity: 45.087,
    poster_path:
      'https://image.tmdb.org/t/p/w500/sqC3z0JMhY11Z1O15lweCzrlepH.jpg',
    release_date: '2018-08-03',
    title: '我的英雄學院 兩個人的英雄',
    video: false,
    vote_average: 7.922,
    vote_count: 996,
  },
  {
    adult: false,
    backdrop_path: '/hph1RMsL4223xyqxfEx3OXodf5E.jpg',
    genre_ids: [28, 16, 878],
    id: 24752,
    original_language: 'ja',
    original_title: 'ドラゴンボールZ とびっきりの最強対最強',
    overview:
      '克維拉在得知弟弟弗利沙被超級賽亞人孫悟空殺害的消息後，便率領克維拉機甲戰隊的沙維札、內茲、德雷來到地球企圖殺死悟空。',
    popularity: 49.747,
    poster_path:
      'https://image.tmdb.org/t/p/w500/sSvkjbKNwtnEYekoVxIFkXFbWut.jpg',
    release_date: '1991-07-20',
    title: '七龍珠Z：最強對最強',
    video: false,
    vote_average: 7,
    vote_count: 668,
  },
  {
    adult: false,
    backdrop_path: '/cUPj0zsNmTbczOh8SwlR8CB6DXt.jpg',
    genre_ids: [16, 28, 878, 18, 14],
    id: 39323,
    original_language: 'ja',
    original_title:
      'ドラゴンボールZ たったひとりの最終決戦〜フリーザに挑んだZ戦士 孫悟空の父〜',
    overview:
      '電視電影特別篇，故事的前傳  弗里薩帝國最為強盛時期，其軍團所到之處望風披靡，無數有文明存在的星球接連成為他的附屬和商品，即使一向驍勇善戰而聞名的賽亞人也臣服於弗里薩的麾下，心甘情願成為他攻城拔寨的馬前卒。孫悟空的父親巴達克是一名低等賽亞人戰士，在和夥伴們入侵某星球時，他遭到當地人的襲擊，從此具有了預測未來的能力。他所看到的，不是民族光輝的未來，而是賽亞人因不斷強大而遭致弗里薩忌憚繼而被滅亡的悲慘命運。療傷期間，小隊夥伴受命前往攻擊臨近星球，結果全部被多多利亞殺害。隨後趕到的巴達克發現預言全部為真，因此急忙趕回貝吉塔行星，準備召集族人與弗里薩決一死戰，但這注定是一場孤獨的戰爭……',
    popularity: 69.994,
    poster_path:
      'https://image.tmdb.org/t/p/w500/9Z5a7VKZiXkPE9i04qizjHKPiAf.jpg',
    release_date: '1990-10-17',
    title: '七龍珠Z：一夫當關的最終決戰 ～向弗利沙挑戰的Z戰士孫悟空之父～',
    video: false,
    vote_average: 7.5,
    vote_count: 690,
  },
  {
    adult: false,
    backdrop_path: '/8NEvnVKeGMLEXG45MMNqxJLcM4y.jpg',
    genre_ids: [16, 28, 14, 53],
    id: 820232,
    original_language: 'ja',
    original_title: '鬼滅の刃 兄妹の絆',
    overview:
      '大正時代，竈門炭治郎繼承亡父留下的炭業工作，支撐一家七口，在山上過著樸實的生活。某日他做完生意返家後發現全家遭到鬼舞辻無慘屠殺，而妹妹禰豆子雖然倖存但變成了鬼。鬼殺隊隊員富岡義勇見狀後本欲斬殺禰豆子，但他在見識到兄妹倆的親情後，推薦炭治郎拜鱗瀧左近次為師。炭治郎經過兩年訓練，學會了對抗鬼的呼吸法與劍術，通過考驗加入鬼殺隊。',
    popularity: 78.234,
    poster_path:
      'https://image.tmdb.org/t/p/w500/iLHaBqrl3k7D9QyVWILPnZdSWMU.jpg',
    release_date: '2019-03-29',
    title: '鬼滅之刃 兄妹之絆',
    video: false,
    vote_average: 7.9,
    vote_count: 205,
  },
  {
    adult: false,
    backdrop_path: '/beLRAtfM6MZxMcPuuJaOmWgcFQC.jpg',
    genre_ids: [16, 35],
    id: 1211716,
    original_language: 'ja',
    original_title: '大室家 dear friends',
    overview: '',
    popularity: 45.68,
    poster_path:
      'https://image.tmdb.org/t/p/w500/v5ScMAHqb66ItRjZX6RzrgOPlFN.jpg',
    release_date: '2024-06-21',
    title: '大室家 dear friends',
    video: false,
    vote_average: 7.9,
    vote_count: 6,
  },
  {
    adult: false,
    backdrop_path: '/1EAxNqdkVnp48a7NUuNBHGflowM.jpg',
    genre_ids: [16, 28, 878, 18],
    id: 283566,
    original_language: 'ja',
    original_title: 'シン・エヴァンゲリオン劇場版:||',
    overview:
      '這是《福音戰士新劇場版》的第四部，也是最終版。美里以及她的反 NERV 组織 Wille 來到巴黎，這裡被核心染成红色，奇蹟號戰艦的船員降落在安全塔上，他們只有 720 秒能修復這個城市。NERV 的福音戰士群出現時，真理的 EVA 改八號機進行攔截。與此同時，真嗣、明日香和零（暫稱）在日本的土地上徘徊。',
    popularity: 51.466,
    poster_path:
      'https://image.tmdb.org/t/p/w500/m4pgO8iyafIrbjN1hJ7hAOsQfjo.jpg',
    release_date: '2021-03-08',
    title: '新世紀福音戰士新劇場版：終',
    video: false,
    vote_average: 8.2,
    vote_count: 806,
  },
  {
    adult: false,
    backdrop_path: '/qoEtWmah7Kqs2USYHNrWSuXuAG8.jpg',
    genre_ids: [16, 80, 9648, 28],
    id: 1209217,
    original_language: 'ja',
    original_title: '名探偵コナン 100万ドルの五稜星（みちしるべ）',
    overview:
      '怪盜基德對斧江財團位於北海道函館的收藏庫發出了預告信，然而奇怪的是，向來只愛盜取名貴珠寶的基德，這次鎖定的目標竟然是一把幕末時代的日本刀。在此同時，柯南與關西名偵探服部平次，正巧為了劍道大會也來到了函館，面對神秘的殺人事件以及基德的公然挑戰，柯南與平次能否成功阻止基德？而秘藏在刀裡的驚人真相又究竟為何？',
    popularity: 65.94,
    poster_path:
      'https://image.tmdb.org/t/p/w500/mnRuwTSE6pm3m89QyCzcsHKaFn3.jpg',
    release_date: '2024-04-12',
    title: '名偵探柯南：100萬美元的五稜星',
    video: false,
    vote_average: 6.7,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: '/2P3R5sSvPjlbkh4ZnVPqjck0iW5.jpg',
    genre_ids: [16, 878, 28],
    id: 610150,
    original_language: 'ja',
    original_title: 'ドラゴンボール超 スーパーヒーロー',
    overview:
      '過去被悟空剷除的反派組織「紅緞帶軍團」再度出現於世人面前，這次他們即將藉由全新的人造人珈瑪 1 號、2 號展開復仇大業。發現異樣的比克前往了紅緞帶軍團的基地探查，卻在那邊發現了「最兇兵器」的存在。而悟飯因為小芳被拐走的關係，來到了基地並且與紅緞帶軍團展開激鬥。究竟戰鬥的結果為何？地球未來的命運又將何去何從？',
    popularity: 73.245,
    poster_path:
      'https://image.tmdb.org/t/p/w500/7d0DJisBVtllXgarSBJOjZKfJMn.jpg',
    release_date: '2022-06-11',
    title: '七龍珠超：超級英雄',
    video: false,
    vote_average: 7.9,
    vote_count: 2814,
  },
  {
    adult: false,
    backdrop_path: '/fy8bBNQyKtRnznm3G3QWdu2wIC8.jpg',
    genre_ids: [12, 28, 16, 35, 14],
    id: 347201,
    original_language: 'ja',
    original_title: 'BORUTO -NARUTO THE MOVIE-',
    overview:
      '以第七代火影∙漩渦鳴人治理的木葉忍者村為中心，五大國共同開展為了培育新忍者的「中忍選拔考試」。村內下忍為了這場考試而不分晝夜地修練，當然也包含了：身為佐助之女卻憧憬鳴人的紗羅妲、被眾多謎團包圍的超優秀下忍光希、以及擁有才能卻稱呼鳴人為臭老爸的慕留人。其中，慕留人雖然身為木葉英雄漩渦鳴人的兒子，卻沒因此而喜歡父親。慕留人懷抱著完全否定父親鳴人，並且超越父親的想法，於是懇求身為父親永遠的對手∙宇智波佐助收他為徒，決定寫出屬於自己的全新故事，讓父親對他另眼相看！',
    popularity: 82.326,
    poster_path:
      'https://image.tmdb.org/t/p/w500/2YW6zJnSTAsgDRvaU0CAj0nrmXz.jpg',
    release_date: '2015-08-07',
    title: '火影忍者劇場版：慕留人',
    video: false,
    vote_average: 7.459,
    vote_count: 1555,
  },
];
